import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782026143019 implements MigrationInterface {
    name = 'InitialSchema1782026143019'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'USER', 'BUSINESS_OWNER', 'DELIVERY_PROVIDER')`);
        await queryRunner.query(`CREATE TABLE "users" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "address" character varying(255), "phone_number" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "modified_at" TIMESTAMP NOT NULL DEFAULT now(), "role" "public"."users_role_enum" NOT NULL DEFAULT 'USER', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "business_owners" ("owner_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone_number" character varying(255) NOT NULL, "address" character varying(255), "city" character varying(255), "country" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_68d6c9c5178f8d4b0d3b0306535" UNIQUE ("email"), CONSTRAINT "PK_20caa301a940a5dbbca4a66d9f3" PRIMARY KEY ("owner_id"))`);
        await queryRunner.query(`CREATE TABLE "businesses" ("business_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "business_name" character varying(255) NOT NULL, "business_address" text NOT NULL, "phone" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "owner_id" uuid, CONSTRAINT "PK_55dfa4b6a716a3ace9d99fd907e" PRIMARY KEY ("business_id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("product_id" character varying(255) NOT NULL, "product_name" character varying(255) NOT NULL, "description" text NOT NULL, "price" numeric(10,2) NOT NULL, "image_url" character varying(255), "stock_quantity" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "businessIdBusinessId" uuid, CONSTRAINT "PK_a8940a4bf3b90bd7ac15c8f4dd9" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("review_id" character varying(255) NOT NULL, "rating" numeric(8,2) NOT NULL, "review_text" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userIdUserId" uuid, "businessIdBusinessId" uuid, "productIdProductId" character varying(255), CONSTRAINT "PK_bfe951d9dca4ba99674c5772905" PRIMARY KEY ("review_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_order_status_enum" AS ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("order_id" character varying(255) NOT NULL, "total_amount" numeric(10,2) NOT NULL, "order_status" "public"."orders_order_status_enum" NOT NULL DEFAULT 'PENDING', "delivery_time" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "modified_at" TIMESTAMP NOT NULL DEFAULT now(), "userIdUserId" uuid, "businessIdBusinessId" uuid, CONSTRAINT "PK_cad55b3cb25b38be94d2ce831db" PRIMARY KEY ("order_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("payment_id" character varying(255) NOT NULL, "amount" numeric(10,2) NOT NULL, "payment_status" "public"."payments_payment_status_enum" NOT NULL DEFAULT 'PENDING', "payment_date" TIMESTAMP NOT NULL DEFAULT now(), "orderIdOrderId" character varying(255), CONSTRAINT "PK_8866a3cfff96b8e17c2b204aae0" PRIMARY KEY ("payment_id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("order_item_id" character varying(255) NOT NULL, "quantity" integer NOT NULL, "item_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "orderIdOrderId" character varying(255), "productIdProductId" character varying(255), CONSTRAINT "PK_54c952fdc94b9b487ef968b4047" PRIMARY KEY ("order_item_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."deliveries_delivery_status_enum" AS ENUM('PENDING', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "deliveries" ("delivery_id" character varying(255) NOT NULL, "delivery_status" "public"."deliveries_delivery_status_enum" NOT NULL DEFAULT 'PENDING', "delivery_address" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "modified_at" TIMESTAMP NOT NULL DEFAULT now(), "orderIdOrderId" character varying(255), "deliveryPersonDeliveryPersonId" character varying(255), CONSTRAINT "PK_91135f316d7af8faf5bfce6fb35" PRIMARY KEY ("delivery_id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_person" ("delivery_person_id" character varying(255) NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "phone_number" character varying(255) NOT NULL, "vehicle_type" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da0da1b54f7b7a1838b69c90cc9" PRIMARY KEY ("delivery_person_id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "parent_id" uuid, CONSTRAINT "UQ_23c05c292c439d77b0de816b500" UNIQUE ("name"), CONSTRAINT "UQ_cb73208f151aa71cdd78f662d70" UNIQUE ("slug"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL DEFAULT 'Unnamed Product', "price" numeric(10,2) NOT NULL DEFAULT '0', "description" text, "ingredients" text, "allergens" text array NOT NULL DEFAULT '{}', "kitchenAllergens" text array NOT NULL DEFAULT '{}', "dietaryLabel" character varying(255), "calories" integer, "macronutrients" text, "category" character varying(100), "seasonStartMonth" integer, "seasonEndMonth" integer, "size" character varying(50) NOT NULL DEFAULT 'Standard size', "weight" character varying(50), "shelfLife" character varying(255), "storageInstructions" text, "seasonalAvailability" character varying(50), "servingSuggestions" text, "variations" text, "customizationOptions" text, "stockQuantity" integer NOT NULL DEFAULT '0', "trackStock" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT true, "leadTimeDays" integer, "maxOrderQuantity" integer, "unitLabel" character varying(100), "rating" integer NOT NULL DEFAULT '0', "reviewCount" integer NOT NULL DEFAULT '0', "images" jsonb NOT NULL DEFAULT '[]', "options" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "category_id" uuid, "businessId" uuid, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22cc43e9a74d7498546e9a63e7" ON "product" ("name") `);
        await queryRunner.query(`CREATE TABLE "business" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "businessName" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "businessType" character varying NOT NULL, "address" character varying NOT NULL, "phoneNumber" character varying NOT NULL, "agreeToTerms" boolean NOT NULL, "isAcceptingOrders" boolean NOT NULL DEFAULT true, "isSuspended" boolean NOT NULL DEFAULT false, "suspensionReason" text, "hygieneCertificateNumber" character varying(100), "hygieneCertificateExpiry" date, "hygieneCertificateVerified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4cca40c3813d4b88a83edb459bc" UNIQUE ("email"), CONSTRAINT "PK_0bd850da8dafab992e2e9b058e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "totalAmount" numeric(10,2) NOT NULL DEFAULT '0', "status" "public"."order_status_enum" NOT NULL DEFAULT 'PENDING', "deliveryAddress" text, "notes" text, "currency" character varying(10) NOT NULL DEFAULT 'gbp', "requestedDeliveryDate" date, "deliverySlotId" character varying, "deliveryFee" numeric(10,2) NOT NULL DEFAULT '0', "discountCodeId" character varying, "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "customer_id" uuid, "business_id" uuid, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_status" ON "order" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_order_business_created" ON "order" ("business_id", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL, "unitPrice" numeric(10,2) NOT NULL, "lineTotal" numeric(10,2) NOT NULL, "order_id" uuid, "product_id" uuid, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_item_order" ON "order_item" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "review" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer NOT NULL, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "product_id" uuid, CONSTRAINT "PK_2e4299a343a81574217255c00ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stripePaymentIntentId" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'gbp', "status" "public"."payment_status_enum" NOT NULL DEFAULT 'PENDING', "stripeRefundId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "refundedAt" TIMESTAMP, "order_id" uuid, CONSTRAINT "UQ_aaf4912b634282efbc202ebd4d1" UNIQUE ("stripePaymentIntentId"), CONSTRAINT "REL_f5221735ace059250daac9d980" UNIQUE ("order_id"), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discount_code_type_enum" AS ENUM('PERCENTAGE', 'FIXED_AMOUNT')`);
        await queryRunner.query(`CREATE TABLE "discount_code" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "type" "public"."discount_code_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "minimumOrderAmount" numeric(10,2), "maxUses" integer, "usedCount" integer NOT NULL DEFAULT '0', "maxUsesPerCustomer" integer, "validFrom" TIMESTAMP NOT NULL, "validUntil" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "business_id" uuid, CONSTRAINT "UQ_9f3bda83ef88511179d386a6b15" UNIQUE ("code"), CONSTRAINT "PK_5119d6f26e6b4c536fd3c67a37d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_slot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "slotStart" TIME NOT NULL, "slotEnd" TIME NOT NULL, "capacity" integer NOT NULL DEFAULT '1', "bookedCount" integer NOT NULL DEFAULT '0', "type" character varying(20) NOT NULL DEFAULT 'DELIVERY', "isActive" boolean NOT NULL DEFAULT true, "heldUntil" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "business_id" uuid, CONSTRAINT "PK_4c95380ca17de88b2c4909659c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discount_code_usage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "usedAt" TIMESTAMP NOT NULL DEFAULT now(), "discount_code_id" uuid, "user_id" uuid, "order_id" uuid, CONSTRAINT "PK_8e5e88f3cbf4f02e2e06221030e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."custom_order_request_status_enum" AS ENUM('PENDING', 'QUOTED', 'ACCEPTED', 'DECLINED', 'DEPOSIT_PAID', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "custom_order_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" text NOT NULL, "itemType" character varying(100), "requestedDate" date, "servings" integer, "dietaryRequirements" text, "referenceImages" text, "status" "public"."custom_order_request_status_enum" NOT NULL DEFAULT 'PENDING', "quotedPrice" numeric(10,2), "depositAmount" numeric(10,2) NOT NULL DEFAULT '0', "businessNotes" text, "quoteExpiresAt" TIMESTAMP, "currency" character varying(10) NOT NULL DEFAULT 'gbp', "deliveryAddress" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "customer_id" uuid, "business_id" uuid, CONSTRAINT "PK_5dc2173e92911a7b375c3558d77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_8881b96819252080592fe1592ea" FOREIGN KEY ("owner_id") REFERENCES "business_owners"("owner_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_8bac6db84cb94daed441afbb9a2" FOREIGN KEY ("businessIdBusinessId") REFERENCES "businesses"("business_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bc2991e017d81c5c504eac473ba" FOREIGN KEY ("userIdUserId") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_2388773344af7783a06e34c2745" FOREIGN KEY ("businessIdBusinessId") REFERENCES "businesses"("business_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_4ae8da753aa31e6d04af7b64d7d" FOREIGN KEY ("productIdProductId") REFERENCES "products"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_213662113ff242f629379d0f676" FOREIGN KEY ("userIdUserId") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_033666bac6c05b63795a8f0df6d" FOREIGN KEY ("businessIdBusinessId") REFERENCES "businesses"("business_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_a30521e61a262a70f37d40b128a" FOREIGN KEY ("orderIdOrderId") REFERENCES "orders"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_b64951c0579cbd203ed3e982c56" FOREIGN KEY ("orderIdOrderId") REFERENCES "orders"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_e1feb6a79d58405cf1d2c3239a3" FOREIGN KEY ("productIdProductId") REFERENCES "products"("product_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_0a0895a8a215868493b15f2594c" FOREIGN KEY ("orderIdOrderId") REFERENCES "orders"("order_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deliveries" ADD CONSTRAINT "FK_1d5fec82fa7f7d9d23e3075527f" FOREIGN KEY ("deliveryPersonDeliveryPersonId") REFERENCES "delivery_person"("delivery_person_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743" FOREIGN KEY ("parent_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_8b95800811275dd98a888044d50" FOREIGN KEY ("businessId") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_cd7812c96209c5bdd48a6b858b0" FOREIGN KEY ("customer_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_173a31627697e0e1a4ff1982fb0" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e9674a6053adbaa1057848cddfa" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_81446f2ee100305f42645d4d6c2" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "review" ADD CONSTRAINT "FK_26b533e15b5f2334c96339a1f08" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_f5221735ace059250daac9d9803" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_code" ADD CONSTRAINT "FK_13d75ce0834b125d80560c711b9" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_slot" ADD CONSTRAINT "FK_44916b3bd36f80d3e1a302f8a1c" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" ADD CONSTRAINT "FK_c2dc66153370c474ea25808939b" FOREIGN KEY ("discount_code_id") REFERENCES "discount_code"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" ADD CONSTRAINT "FK_edbfafcb55649e686aab071bb48" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" ADD CONSTRAINT "FK_af10afedaab89554e5b26327bb1" FOREIGN KEY ("order_id") REFERENCES "order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_request" ADD CONSTRAINT "FK_b22faa0d319c4998ae3ce4b32a0" FOREIGN KEY ("customer_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_request" ADD CONSTRAINT "FK_31e92a395599a2094458469f5a6" FOREIGN KEY ("business_id") REFERENCES "business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "custom_order_request" DROP CONSTRAINT "FK_31e92a395599a2094458469f5a6"`);
        await queryRunner.query(`ALTER TABLE "custom_order_request" DROP CONSTRAINT "FK_b22faa0d319c4998ae3ce4b32a0"`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" DROP CONSTRAINT "FK_af10afedaab89554e5b26327bb1"`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" DROP CONSTRAINT "FK_edbfafcb55649e686aab071bb48"`);
        await queryRunner.query(`ALTER TABLE "discount_code_usage" DROP CONSTRAINT "FK_c2dc66153370c474ea25808939b"`);
        await queryRunner.query(`ALTER TABLE "delivery_slot" DROP CONSTRAINT "FK_44916b3bd36f80d3e1a302f8a1c"`);
        await queryRunner.query(`ALTER TABLE "discount_code" DROP CONSTRAINT "FK_13d75ce0834b125d80560c711b9"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_f5221735ace059250daac9d9803"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_26b533e15b5f2334c96339a1f08"`);
        await queryRunner.query(`ALTER TABLE "review" DROP CONSTRAINT "FK_81446f2ee100305f42645d4d6c2"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_5e17c017aa3f5164cb2da5b1c6b"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e9674a6053adbaa1057848cddfa"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_173a31627697e0e1a4ff1982fb0"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_cd7812c96209c5bdd48a6b858b0"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_8b95800811275dd98a888044d50"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_1117b4fcb3cd4abb4383e1c2743"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_1d5fec82fa7f7d9d23e3075527f"`);
        await queryRunner.query(`ALTER TABLE "deliveries" DROP CONSTRAINT "FK_0a0895a8a215868493b15f2594c"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_e1feb6a79d58405cf1d2c3239a3"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_b64951c0579cbd203ed3e982c56"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_a30521e61a262a70f37d40b128a"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_033666bac6c05b63795a8f0df6d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_213662113ff242f629379d0f676"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_4ae8da753aa31e6d04af7b64d7d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_2388773344af7783a06e34c2745"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bc2991e017d81c5c504eac473ba"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_8bac6db84cb94daed441afbb9a2"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_8881b96819252080592fe1592ea"`);
        await queryRunner.query(`DROP TABLE "custom_order_request"`);
        await queryRunner.query(`DROP TYPE "public"."custom_order_request_status_enum"`);
        await queryRunner.query(`DROP TABLE "discount_code_usage"`);
        await queryRunner.query(`DROP TABLE "delivery_slot"`);
        await queryRunner.query(`DROP TABLE "discount_code"`);
        await queryRunner.query(`DROP TYPE "public"."discount_code_type_enum"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "review"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_item_order"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_business_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "business"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22cc43e9a74d7498546e9a63e7"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "delivery_person"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP TYPE "public"."deliveries_delivery_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_order_status_enum"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP TABLE "business_owners"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
